image: Visual Studio 2017

platform: x64

cache:
  - c:\miktex -> appveyor.yml

install:
  # - appveyor-retry choco install -y miktex.portable
  # Install miktex to get pdflatex, if we don't get it from the cache
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile http://mirror.utexas.edu/ctan/systems/win32/miktex/setup/windows-x86/miktex-portable.exe
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable.exe -oC:\miktex >NUL
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin;"
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - initexmf --set-config-value "[MPM]AutoInstall=1"
  - cmd: git submodule update --init --recursive
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  - ps: Bootstrap
  - cp -r c:\R64\Tcl r-source\Tcl
  - cmd: .\scripts\msys2.cmd
  - cp -r qpdf c:\qpdf

# environment:

build_script:
  - ECHO %PATH%
  - cp src/gnuwin32/MkRules.local r-source/src/gnuwin32/.
  - cp src/main/Makefile.win r-source/src/main/.
  - cp src/extra/blas/Makefile.win r-source/src/extra/blas/.

  - gcc --version
  - gfortran --version

  - cd r-source/src/gnuwin32
  - make rsync-recommended
  - make rsync-extsoft

  - SET TMPDIR=C:/Users/appveyor/AppData/Local/Temp

  - make all
  - make distribution
